//------------------------------------------------------------------------------
//                Add PPP . do
//------------------------------------------------------------------------------

use "$work_data/ppp.dta", clear

// Add exchage rate with EUR and CNY
// New round does not have EA, we take an average of Euro countries
merge n:1 year using "$work_data/ppp_ea_cn_weithgted.dta", nogenerate

generate valuexlceup999i = ppp/ppp_ea
generate valuexlcyup999i = ppp/ppp_cn

generate data_qualityxlceup999i = min(data_quality,q_ea)
generate data_qualityxlcyup999i = min(data_quality,q_cn)


rename ppp valuexlcusp999i
rename data_quality data_qualityxlcusp999i
drop ppp_ea ppp_cn q_ea q_cn

reshape long value data_quality, i(iso year) j(widcode) string
replace widcode = widcode
generate p = "pall"
drop if missing(value)

drop if iso == "EA"

// Complete metadata
/*
preserve
	gen sixlet=substr(widcode,1,6)
	drop widcode 
	
	*Identify frontier years
	gen      aux=0 
	replace  aux=1 if year>=1970
	sort iso sixlet year 

	sort iso sixlet aux year

	bysort iso sixlet aux: egen firstyear = min(year)
	bysort iso sixlet aux: egen lastyear = max(year)
	
	
	keep iso  sixlet firstyear lastyear
	
	duplicates drop
	bysort iso sixlet (firstyear lastyear): gen categ = sum(firstyear != firstyear[_n-1] | lastyear  != lastyear[_n-1])

	merge m:1  iso sixlet using "$work_data/ppp-metadata.dta", nogen keep(master match) keepusing(method source)


	* method & source
	replace method= "This indicator was triangulated from xlcusp by a <<Euro xlcusp>> weighting the xlcusp of DE, ES, FR, IT, NL" if missing(method) & sixlet=="xlceup" 
	replace method= "This indicator was triangulated from xlcusp by a xlcusp of CN" if missing(method) & sixlet=="xlcyup"
	
	
	replace source= "In-house calculation" if missing(source)
	
	* Collase the metadata
	foreach v in source method {
		preserve
			generate `v'_new = string(firstyear) + ": " + `v' + ";" ///
				if (firstyear == lastyear) & (`v'!="")
			replace `v'_new = string(firstyear) + "-" + string(lastyear) + ///
				": " + `v' + ";" if  (firstyear != lastyear)  & (`v'!="")
			drop firstyear lastyear 

			keep iso sixlet categ `v'_new 
			drop if `v'_new == ""
			duplicates drop

			greshape wide `v'_new, i(iso sixlet) j(categ)
			egen `v' = concat(`v'_new*), punct(" ")
			keep iso sixlet `v' 
			
			tempfile metadata_`v'
			save    `metadata_`v''
		restore
	}

	u "`metadata_method'", clear
	merge 1:1 iso sixlet using "`metadata_source'", nogen 
	order iso sixlet method source
	
	replace method = substr(method, 1, length(method) - 1)
	replace source = substr(source, 1, length(source) - 1) 

	append using  "$work_data/correct-widcodes-metadata.dta"

	label data "Generated by add-ppp.do"
	save "$work_data/add-ppp-metadata.dta", replace
restore
*/
// Add to WID
append using "$work_data/correct-widcodes-output.dta", gen(old)

// Get rid of PPP/MER from Piketty-Yang-Zucman paper
drop if substr(iso, 1, 2) == "CN" & substr(widcode, 1, 3) == "xlc" & old
drop old

label data "Generated by add-ppp.do"
save "$work_data/add-ppp-output.dta", replace



