*Import Exchange rates
use "$work_data/exchange-rates.dta", clear
cap drop _fillin titlename shortname region* corecountry TH




// ----------- Genrate valuexlceux999i and valuexlcyux999i ---------------------
*Note: This is the former PART Main.10  of the file import-exchange-rate.do
rename exrate_usd xlcusx999i
rename s_ s_xlcusx999i
* call nninc
preserve
   // Bringing net gdp to weight the EUR
	use "$work_data/retropolate-gdp.dta" if currency == "EUR", clear
	drop if iso == "DD"

	keep iso year gdp currency
	
	tempfile eurgdp
	save `eurgdp'
restore

* Generate ratios to EUR pre-1999
preserve 
	keep if year<1999
	keep if currency == "EUR" ///	
						& (inlist(iso, "DE", "ES", "FR", "IT", "NL")) 
						
	merge 1:1 iso year using `eurgdp', nogen keep( master match)
	bysort year: egen q_ea = mode(data_quality)
    * duplicates drop year, force
	
	collapse (first) q_ea (mean) xlcusx999i [aweight=gdp], by(year)
	rename xlcusx999i EURUSDpre
	
	tempfile eurusdpre99
	save "`eurusdpre99'"
restore

* Generate ratios to EUR post-1999
preserve 
	keep if year>=1999
	keep if currency == "EUR" ///	
						& (inlist(iso, "DE", "ES", "FR", "IT", "NL")) 

//	duplicates drop year, force
	bysort year: egen q_ea = mode(data_quality)
	collapse  (first) q_ea (mean) xlcusx999i, by(year)
	rename xlcusx999i EURUSDpos
	
	tempfile eurusdpos99
	save "`eurusdpos99'"
restore

* Generate ratios to CNY
preserve
	keep if currency == "CNY"
	keep year xlcusx999i data_quality
	duplicates drop year, force
	rename xlcusx999i CNYUSD
	rename data_quality q_cn
	
	tempfile cnyusd
	save "`cnyusd'"
restore


* Merge ratios
merge n:1 year using "`eurusdpre99'", keep(master match) nogenerate
merge n:1 year using "`eurusdpos99'", keep(master match) nogenerate 
merge n:1 year using "`cnyusd'", keep(master match) nogenerate

*Compile ratios of EUR
gen     EURUSD = EURUSDpos 
replace EURUSD = EURUSDpre if missing(EURUSD)

preserve
	keep year EURUSD CNYUSD q_ea q_cn
	rename (EURUSD CNYUSD)(xr_ea xr_cn)
	rename ( q_ea q_cn)(q_xr_ea q_xr_cn)
	duplicates drop
	
	label data " Generated by add-exchange-rates.do"
	save "$work_data/xrate_ea_cn_weithgted.dta", replace
restore

* Triangulate exchange rate to EUR
gen xlceux999i = xlcusx999i/EURUSD
gen xlcyux999i = xlcusx999i/CNYUSD

gen data_qualityxlceux999i = min(q_ea, data_quality)
gen data_qualityxlcyux999i = min(q_cn, data_quality)
gen s_xlceux999i = "triang"
gen s_xlcyux999i = "triang"


drop EURUSD* CNYUSD q_*

//------------------------------------------------------------------------------
* Notes: The value of the EUR for the triangulation should be a median of countries
*        The final data_quality of the countries should be done with a min between the indicators.
//------------------------------------------------------------------------------

* Check that eur is behaving as expected 
replace xlceux999i = round(xlceux999i) if currency == "EUR" & year >= 1999 ///
& ( ///
    (inlist(iso, "AT","BE","DD","DE","ES","FI") & year >= 1999) | ///
    (inlist(iso, "FR","IE","IT","LU","NL","PT") & year >= 1999) | ///
    (iso == "GR" & year >= 2001) | ///
    (inlist(iso, "AD","MC","ME","MF","SM") & year >= 2002) | ///
    (iso == "SI" & year >= 2007) | ///
    (inlist(iso, "CY","MT") & year >= 2008) | ///
    (iso == "SK" & year >= 2009) | ///
    (iso == "EE" & year >= 2011) | ///
    (iso == "LV" & year >= 2014) | ///
    (iso == "LT" & year >= 2015) | ///
    (iso == "HR" & year >= 2023) ///
)

* check that currencies are consistent to theirselves.
//assert xlceux999i == 1 if currency == "EUR" & year > 1999
assert xlcyux999i == 1 if currency == "CNY"
assert xlcusx999i == 1 if currency == "USD"

*format for adding to the WID
rename (xlcusx999i xlceux999i xlcyux999i)(valuexlcusx999i valuexlceux999i valuexlcyux999i)
rename data_quality data_qualityxlcusx999i
reshape long value data_quality s_, i(iso year p currency) j(widcode) string

sort iso widcode year

tempfile full_data
save `full_data'
/*
// Complete metadata
gen sixlet=substr(widcode,1,6)
drop widcode 
	
*Identify frontier years
gen      aux=0 
replace  aux=1 if year>=1970
sort iso sixlet year 

sort iso sixlet aux year

bysort iso sixlet aux: egen firstyear = min(year)
bysort iso sixlet aux: egen lastyear = max(year)
	
keep iso  sixlet firstyear lastyear
	
duplicates drop
bysort iso sixlet (firstyear lastyear): gen categ = sum(firstyear != firstyear[_n-1] | lastyear  != lastyear[_n-1])

	
merge m:1  iso sixlet using "$work_data/exchange-rates-metadata.dta", nogen keep(master match) keepusing(method source)

* method & source
replace method= "This indicator was triangulated from xlcusx by a <<Euro xlcusx>> weighting the xlcusp of DE, ES, FR, IT, NL" if missing(method) & sixlet=="xlceux" 
replace method= "This indicator was triangulated from xlcusx by a xlcusx of CN" if missing(method) & sixlet=="xlcyux"
replace method="Observed data" if missing(method) & sixlet=="xlcusx"
	
replace source= "In-house calculation" if missing(source)
	
* Collase the metadata
foreach v in source method {
	preserve
		generate `v'_new = string(firstyear) + ": " + `v' + ";" ///
			if (firstyear == lastyear) & (`v'!="")
		replace `v'_new = string(firstyear) + "-" + string(lastyear) + ///
			": " + `v' + ";" if  (firstyear != lastyear)  & (`v'!="")
		drop firstyear lastyear 

		keep iso sixlet categ `v'_new 
		drop if `v'_new == ""
		duplicates drop

		greshape wide `v'_new, i(iso sixlet) j(categ)
		egen `v' = concat(`v'_new*), punct(" ")
		keep iso sixlet `v' 
			
		tempfile metadata_`v'
		save    `metadata_`v''
	restore
}

u "`metadata_method'", clear
merge 1:1 iso sixlet using "`metadata_source'", nogen 
order iso sixlet method source
	
replace method = substr(method, 1, length(method) - 1)
replace source = substr(source, 1, length(source) - 1) 
	
gen new=1

append using  "$work_data/add-ppp-metadata.dta"
	
duplicates tag iso sixlet, gen(dup)	
drop if new!=1 & dup!=0
duplicates tag iso sixlet, gen(dup2)	
assert dup2==0
drop dup* new
	
label data "Generated by add-exchange-rates.do"
save "$work_data/add-exchange-rates-metadata.dta", replace

*/
//---------------Append the rest of the WID Data -------------------------------
u "`full_data'", clear
append using "$work_data/add-ppp-output.dta"

// Add Chinese exchange rates to urban and rural China
drop if inlist(iso, "CN-UR", "CN-RU") & substr(widcode, 1, 3) == "xlc"

expand 2 if (iso == "CN") & substr(widcode, 1, 3) == "xlc", generate(newobs)
replace iso = "CN-UR" if newobs
drop newobs

expand 2 if (iso == "CN") & substr(widcode, 1, 3) == "xlc", generate(newobs)
replace iso = "CN-RU" if newobs
drop newobs

compress
label data "Generated by add-exchange-rates.do"
save "$work_data/add-exchange-rates-output.dta", replace
