// -------------------------------------------------------------------------- //
// Add Price index series to the database
// -------------------------------------------------------------------------- //

clear all
tempfile updates
save `updates', emptyok

//-------- 1. Price index
* Call price index
use "$work_data/price-index.dta", clear
rename index value
generate p = "pall"
generate widcode = "inyixx999i"
tempfile priceindex
save "`priceindex'"

//-------- 2. Price index Local currency unit change
* Call Local currency unit change indicator 
* Note: i.e. change in local currency unit: e.g. FF, DM, etc. become EUR in 1999, etc.)
* Import Data
use "$work_data/nievaspiketty2025_70.dta", clear
drop if inlist(substr(iso, 1, 1), "X", "O") | inlist(iso, "QL","QM","WO","QE")
keep if  widcode == "intlcu999i"
rename q_ data_quality
 
recast double value
preserve
	sort iso year 
	* Keep the last year available in the NP2025 dataset
	keep if year==2022

	*Generate the number of duplicates needed
	local n_dup =  ($pastyear - 2022) // $pastyear
	
	
	if `n_dup'!=0 {  // Loop for filling missing recent years
	* Expand 
	expand `n_dup'
	bysort iso widcode p: gen cnt=_n
	replace year=year+cnt 

	* Clean up
	drop cnt

	save "`updates'", replace

restore

append using "`updates'"
** Manual Corrections if necessary
	} 
else { //* Loop in case NP2025 is up to the date
restore
	}
sort iso year

tempfile indexchange
save "`indexchange'"

//-------- 3. Metadata
/*
* Identify new observations
use "`priceindex'", clear
append using "`indexchange'"

gen sixlet = substr(widcode,1,6)
drop widcode 
	
*Identify frontier years
gen      aux=0 
replace  aux=1 if year>=1970
sort iso sixlet year 

sort iso sixlet aux year

bysort iso sixlet aux: egen firstyear = min(year)
bysort iso sixlet aux: egen lastyear = max(year)
	
keep iso  sixlet firstyear lastyear s_
	
duplicates drop
bysort iso sixlet (firstyear lastyear): gen categ = sum(firstyear != firstyear[_n-1] | lastyear  != lastyear[_n-1])

* Bring metadata of Price index
merge m:1 iso sixlet using "$work_data/price-index-metadata.dta", nogen keep(master match)

*Complete metadata
replace source=`"[URL][URL_LINK]https://wid.world/document/unequal-exchange-and-north-south-relations-evidence-from-global-trade-flows-and-the-world-balance-of-payments-1800-2025-world-inequality-lab-working-paper-2025-11/[/URL_LINK]"' ///
		+ `"[URL_TEXT]Nievas, G., Piketty, T. (2025) Unequal Exchange and North-South Relations: Evidence from Global Trade Flows and the World Balance of Payments 1800-2025[/URL_TEXT][/URL]"' if strpos(s_,"np2025")

replace method = "Observed data" if strpos(s_,"np2025")
drop s_

* Collase the metadata
foreach v in source method {
	preserve
		generate `v'_new = string(firstyear) + ": " + `v' + ";" ///
				if (firstyear == lastyear) & (`v'!="")
		replace `v'_new = string(firstyear) + "-" + string(lastyear) + ///
				": " + `v' + ";" if  (firstyear != lastyear)  & (`v'!="")
		drop firstyear lastyear 

		keep iso sixlet categ `v'_new 
		drop if `v'_new == ""
		duplicates drop

		greshape wide `v'_new, i(iso sixlet) j(categ)
		egen `v' = concat(`v'_new*), punct(" ")
		keep iso sixlet `v' 
			
		tempfile metadata_`v'
		save    `metadata_`v''
	restore
}

u "`metadata_method'", clear
merge 1:1 iso sixlet using "`metadata_source'", nogen 
order iso sixlet method source



duplicates tag iso sixlet, gen(dup)
assert dup==0
drop dup

append using "$work_data/add-exchange-rates-metadata.dta"

label data "Generated by add-price-index.do"
save "$work_data/add-price-index-metadata.dta", replace
*/

//-------- 4. Integrate to WID
*Call data from WID
use "$work_data/convert-to-real-output.dta", clear
drop if (widcode == "inyixx999i") | (widcode == "icpixx999i")

*Append price indexes
append using "`priceindex'"
append using "`indexchange'"
*drop s_

sort iso widcode p year

*complete currency by country
egen currency2 = mode(currency), by(iso)
drop currency
rename currency2 currency

order iso year widcode p value currency

compress
label data "Generated by add-price-index.do"
save "$work_data/add-price-index-output.dta", replace

