// ---------------------------------------------------------------------------
// IMPORT ALL FILES
// ---------------------------------------------------------------------------

// Objective: This file adds new data provided by researchers to WID, 
// pre-cleaned in their respective folders.

// WARNING: There must a good reason for adding add directly in real rather
// than in nominal. Data imported directly in real terms will not be properly
// updated to last year's prices during the annual update unless it is handled
// correctly by calibrate-dina.do.
// (Regional data is the most common use case for the part of the code.)

// Latest modifications: A. Van Der Ree, 23 Oct 2025

//--------------------- INDEX ----------------------------------------------//
//       1. Import data
//       	  1.1 import individual country cases 
//       	  1.2 Import updated pre-tax series (2025 update)
//       	  1.3 Import updated post-tax series
//       	  1.4. Import 40 additional pre-tax countries 
//       	  1.5. Saving researchers data (tempfile)
//       2. Import meta data
//       	  2.1 Import individual country cases
//       	  2.2 Set up meta data variables
//       	  2.3 Import updated pre-tax series (2025 update)
//       	  2.4 Import updated post-tax series
//       	  2.5. Saving researchers meta data (tempfile)
//       3. Add data to WID 
// 		 4. Combine National Accounts and Distributional Meta datas

//----------------------------------------------------------------------------//

// -----------------------------------------------------------------------------
// ----------------------------- 1. Import data  -------------------------------
// -----------------------------------------------------------------------------

//======================= 1.1 import individual country cases ==================

// France inequality 2017 (GGP2017)
use "$wid_dir/Country-Updates/France/2024-ggp/france-ggp2017_Feb2026.dta", clear //Modif: 10 Oct 2024 by Manuel Esteban

// Germany and subregions
append using "$wid_dir/Country-Updates/Germany/2018/May/bartels2018.dta"
// drop if iso == "DE"

gen old=1

// Korea 2018 (Kim2018), only gdp and nni (rest is in current LCU)
append using "$wid_dir/Country-Updates/Korea/2018_10/korea-kim2018-constant.dta"
preserve 
	keep if year<1950 & author == "kim2018"
	tempfile kr
	save `kr'
restore
drop if iso == "KR"
append using `kr'

keep iso year p widcode value author old data_quality

assert !missing(iso, year, widcode)
isid iso year p widcode
//================= 1.2 Import updated pre-tax series (2025 update) ============

									//Below Modif: 14 Nov 2025 by A.Van Der Ree

// Europe (East & West) Countries and Aggregates
// 		- ptinc series 2025 update
// 		- cainc series pulled from 2023 update
append using "$wid_dir/Country-Updates/Europe/2025_10/europe-ptinc-2025"
append using "$wid_dir/Country-Updates/Europe/2025_10/europe-cainc-2025"

drop if inlist(iso, "QX", "QY")

replace iso="QE-PPP" if iso=="QE"
replace iso="QM-PPP" if iso=="QM"

									//Below Modif: 18 Nov 2025 by A.Van Der Ree

// Latin America 						
drop if inlist(iso, "XL", "XL-MER")
append using "$wid_dir/Country-Updates/Latin_America/2025/latin-america-2025.dta" 

assert !missing(iso, year, widcode)
duplicates tag iso year p widcode, gen(dup)
drop if dup == 1 & old == 1
drop dup
isid iso year p widcode

assert !missing(data_quality) if !inlist(iso, "QE-PPP", "QM-PPP") & ///
    (strpos(widcode, "ptinc") | strpos(widcode, "cainc"))


//================= 1.3 Import updated post-tax series =========================

// Post-tax series (Fisher-Post & Gethin 2023)	
										//Modif: 16 Dec 2025 by A.Van Der Ree 
	
append using "$wid_dir/Country-Updates/posttax/12_2025/post-tax-2025.dta" 

//================= 1.4 Import 40 additional pre-tax countries ===================

// 40 new additional countries accoding to the 2024 extension of the database
append using "$wid_dir/Country-Updates/Historical_series/2024_May/forty_additional_countries_ptinc_Feb2026.dta"

assert !missing(iso, year, widcode)
isid iso year p widcode


assert !missing(data_quality) if !inlist(iso, "QE-PPP", "QM-PPP") & ///
    (strpos(widcode, "ptinc") | strpos(widcode, "cainc"))
	
//==================== 1.5 Saving researchers data (tempfile) ==================

compress, nocoalesce 

// ==== Checkpoint 1: (to reduce running time can run after here)
// label data "Checkpoint file generated by add-researchers-data-real.do"
// save "$work_data/aux-1.dta", replace
// use "$work_data/aux-1.dta", clear
//=========

tempfile researchers
save "`researchers'"

// -----------------------------------------------------------------------------
// ------------------------- 2. Import Meta Data  ------------------------------
// -----------------------------------------------------------------------------

//================= 2.1 Import individual countries metadata ===================
// retrieving source and method columns 

merge 1:1 iso year p widcode using"$wid_dir/Country-Updates/France/2024-ggp/france-ggp2017.dta", keepusing(source method) update replace nogen

merge 1:1 iso year p widcode using"$wid_dir/Country-Updates/Germany/2018/May/bartels2018.dta", keepusing(source method) update replace nogen

merge 1:1 iso year p widcode using `kr', keepusing(source method) update replace nogen

//====================== 2.2 Set up metadata variables =========================

generate sixlet = substr(widcode, 1, 6)
drop data_quality
ds year p widcode value currency author old, not
keep `r(varlist)'
order iso sixlet source method
drop if iso == "FR" & missing(source) & strpos(sixlet, "ptinc")
drop if iso == "FR" & strpos(sixlet, "pllin")
duplicates drop
// drop if missing(source) & missing(method)

//================= 2.3 Import updated pre-tax series (2025 update) ============
									
									//Below Modif: 24 Oct 2025 by A.Van Der Ree
// Europe 
// 		- ptinc (updated 2025)
// 		- cainc & diinc (pulled from 2023 metadata)
merge 1:1 iso sixlet using "$wid_dir/Country-Updates/Europe/2025_10/europe-2025-metadata", update replace nogen

drop if iso == "FR" & method == "" & inlist(sixlet, "scainc", "sdiinc", "tptinc")
drop if iso == "FR" & method == "" & strpos(sixlet, "ptinc")
drop if iso == "FR" & method == "" & strpos(sixlet, "pllin")

// Latin America                   
merge 1:1 iso sixlet using "$wid_dir/Country-Updates/Latin_America/2025/latin-america-2025-metadata.dta", force update replace nogen 

//================= 2.4 Import updated post-tax series =========================

// Post-tax series 
merge 1:1 iso sixlet using "$wid_dir/Country-Updates/posttax/12_2025/post-tax-2025-metadata.dta", force update replace nogen //Modif: 5 Jan 2026 by A. Van Der Ree
duplicates drop


duplicates tag iso sixlet, gen(dup)
assert dup==0
drop dup

replace method = " " if method == ""

//================= 2.5 Saving researchers meta data (tempfile) ================

// ==== Checkpoint 2: (to reduce running time can run after here)
// label data "Checkpoint file generated by add-researchers-data-real.do"
// save "$work_data/aux-2.dta", replace
// use "$work_data/aux-2.dta", clear
//===============================

tempfile meta
save "`meta'"

// -----------------------------------------------------------------------------
// ------------------------- 3. Add data to WID --------------------------------
// -----------------------------------------------------------------------------

use iso year p widcode value author data_quality using "`researchers'", clear
// append using "$work_data/aggregate-regions-output.dta", generate(oldobs)
// append using "$work_data/add-populations-output.dta", generate(oldobs)

// ===!========!=======!=============!=======!======!======!====!====!====!====!
// ===!========!=======!=============!=======!======!======!====!====!====!====!
// ===!========!=======!=============!=======!======!======!====!====!====!====!
// ----- TEMPORARY FIX TO BE REMOVED AFTER DATA QUALITY PROJECT IS COMPLETE!!! ---
preserve
	use "$work_data/calculate-per-capita-series-output.dta", clear
	gen sixlet = substr(widcode, 1, 6)
	merge m:1 iso year sixlet using "$work_data/data-quality-add-researchers-data-output.dta"
	drop if _merge == 2 // only from add-researchers
	drop _merge sixlet
	tempfile interimdata
	save `interimdata'
restore 

append using `interimdata', generate(oldobs)
*append using "$work_data/calculate-per-capita-series-output.dta", generate(oldobs)
// ===!========!=======!=============!=======!======!======!====!====!====!====!
// ===!========!=======!=============!=======!======!======!====!====!====!====!
// ===!========!=======!=============!=======!======!======!====!====!====!====!


// France 2017: drop specific widcodes
drop if (inlist(widcode, "ahwbol992j", "ahwbus992j", "ahwcud992j", "ahwdeb992j", "ahweal992j") ///
	   | inlist(widcode, "ahwequ992j", "ahwfie992j", "ahwfin992j", "ahwfix992j", "ahwhou992j") ///
	   | inlist(widcode, "ahwnfa992j", "ahwpen992j", "bhweal992j", "ohweal992j", "shweal992j", "thweal992j") ///
	   | (substr(widcode, 2, 2) == "fi") & substr(widcode, 1, 1) != "m") ///
	   & (iso == "FR") & (oldobs == 1)

replace p = "pall" if p == "p0p100"

// Drop old duplicated wid data
gduplicates tag iso year p widcode if iso == "CZ", gen(duplicate)
drop if duplicate == 1 & iso == "CZ" & oldobs == 1 & author != "bcg2020"
drop duplicate

//------------------- Cleaning :
* Drop old duplicated wid data (same values)
gduplicates tag iso year p widcode, gen(duplicate)
drop if duplicate==1 & oldobs== 1
drop duplicate

* Drop old duplicated wid data (not the same values; we keep the most recent 
* one from this year's update)
gduplicates tag iso year p widcode, gen(duplicate)
drop if duplicate==1 & author=="ggp2017"
drop duplicate
 
gduplicates tag iso year widcode p, gen(duplicate)
assert duplicate==0
drop duplicate
//---------------------------

assert !missing(data_quality) if !inlist(iso, "QE-PPP", "QM-PPP") & ///
    (strpos(widcode, "ptinc") | strpos(widcode, "cainc")) & substr(widcode, 1, 1) != "b" ///
	& !(iso=="US" & widcode=="scainc992j") // exceptions because data quality has not been added yet to these specific cases

keep iso year p widcode currency value //data_quality 

compress
label data "Generated by add-researchers-data-real.do"
save "$work_data/add-researchers-data-real-output.dta", replace

// -----------------------------------------------------------------------------
// ------- 4. Combine National Accounts and Distributional Meta datas ----------
// -----------------------------------------------------------------------------

// use "$work_data/aggregate-regions-metadata-output.dta", clear
use "$work_data/metadata-no-duplicates.dta", clear
drop if iso == "CN" & mi(source) & inlist(sixlet, "xlcusx", "xlcyux")

merge 1:1 iso sixlet using "`meta'", force nogenerate update replace 
replace method = "" if method == " "
*replace method = "" if iso == "FR" & substr(sixlet, 2, 5) == "ptinc"
 
gduplicates tag iso sixlet, gen(duplicate)
assert duplicate == 0
drop duplicate

label data "Generated by add-researchers-data-real.do"
save "$work_data/add-researchers-data-real-metadata.dta", replace

