//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//                         Calculate-coefficients.do                              
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------

// Purpose: To calculate the following coefficients for the entire database
// 		(i)  Top 10 Bottom 50 ratio ("r")
// 		(ii) Pareto coefficient ("b")
//	   (iii) Gini coefficient ("g")

// previously each coefficient was calculated in its own do-file, generating 
// 3 heavy outputs. To lighten the work data folder, we combine it into one output. 

//------------------------- 0. Index -------------------------------------------
// 1. Calculate Top 10 Bottom 50 ratios
// 2. Calculate Pareto coefficients
// 3. Calculate Gini coefficients
// 4. Checks for data quality 
// 5. Export
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// ----- 1. Calculate Top10/Bottom50 ratio for all available income concepts ---
//------------------------------------------------------------------------------

use  "$work_data/homogenize-all-distributions-output.dta", clear
keep if substr(widcode, 1, 1) == "a"
keep if (p == "p90p100" | p == "p0p50")

// Split widcode
generate onelet  = substr(widcode, 1, 1)
generate vartype = substr(widcode, 2, .)

greshape wide value, i(iso year widcode currency onelet vartype data_quality) j(p) string
generate value = valuep90p100/valuep0p50

drop if missing(value)
drop valuep90p100 valuep0p50
replace widcode = "r" + vartype
drop onelet vartype
generate p = "p0p100"

tempfile ratio
save "`ratio'"

// Put pop(i) to pop(j) hweal for GB before 1995
use  "$work_data/homogenize-all-distributions-output.dta", clear
keep if inlist(widcode, "shweal992i", "shweal992j") & iso == "GB"

reshape wide value, i(iso year p currency data_quality) j(widcode) string

replace valueshweal992j = valueshweal992i if year<1995 & missing(valueshweal992j)
reshape long
drop if missing(value)

tempfile shweal992j
save "`shweal992j'"

// save
use  "$work_data/homogenize-all-distributions-output.dta", clear
append using "`ratio'"
merge 1:1 iso year p widcode using "`shweal992j'", nogen

tempfile top10bot50
save `top10bot50'
*label data "Generated by calculate-top10bot50-ratio.do"
*save "$work_data/calculate-top10bot50-ratio.dta", replace

//------------------------------------------------------------------------------
// ----------------------- 2. Calculate pareto coefficients --------------------
//------------------------------------------------------------------------------

*use "$work_data/calculate-top10bot50-ratio.dta", clear

// Keep thresholds and top averages only
keep if inlist(substr(widcode, 1, 1), "a","t")
keep if (substr(widcode, 1, 1) == "a" & regexm(p, "^p([0-9\.]+)p100$")) | ///
	    (substr(widcode, 1, 1) == "t" & regexm(p, "^p([0-9\.]+)p100$"))

// Split widcode
generate onelet = substr(widcode, 1, 1)
generate vartype = substr(widcode, 2, .)

// Get percentile
generate long perc = round(1e3*real(regexs(1))) if (regexm(p, "^p([0-9\.]+)(p100)?$"))
drop p widcode

greshape wide value, i(iso year perc vartype data_quality) j(onelet) string

// Calculate Pareto coefficient
generate value = valuea/valuet
drop if missing(value)
drop valuea valuet

generate widcode = "b" + vartype
drop vartype

generate p = "p" + string(perc/1e3) + "p100"
drop perc

gen new=1

tempfile bp
save "`bp'"

// Add to the data
*use "$work_data/calculate-per-capita-series-carbon-output.dta", clear
*use "$work_data/World-and-regional-aggregates-output.dta", clear
*use "$work_data/calculate-top10bot50-ratio.dta", clear
use `top10bot50'

drop if substr(widcode, 1, 1) == "b"

append using "`bp'"
duplicates tag iso year widcode p, gen (dup)
drop if dup==1 & new!=1
duplicates tag iso year widcode p, gen (dup2)
asser dup2==0
drop dup* new

drop if year > $pastyear

tempfile pareto_coef
save `pareto_coef'
*label data "Generated by calculate-pareto-coef.do"
*save "$work_data/calculate-pareto-coef-output.dta", replace

//------------------------------------------------------------------------------
// ----------------------- 3. Calculate gini coefficients ----------------------
//------------------------------------------------------------------------------

*use "$work_data/calculate-pareto-coef-output.dta", clear

// Keep data for which we can calculate Ginis
keep if regexm(p, "^p(.*)p100$")
keep if substr(widcode, 1, 1) == "s"
sort iso year widcode

// Keep only complete distributions
by iso year widcode: generate nperc = _N
keep if nperc == 127
drop nperc

// Convert percentiles to number
generate pnum = round(1000*real(regexs(1))) if regexm(p, "^p(.*)p100$")
drop p
rename pnum p

//------ Transformation 1 -----------
replace value= value*1000 if substr(widcode,1,1)=="s"
//-----------------------------------

// Calulate the Gini
generate bottom_share = 1000 - value

//------ Transformation 1 -----------
replace value= value/1000 if substr(widcode,1,1)=="s"
replace bottom_share= bottom_share/1000
//-----------------------------------

generate equality_line = p/1e5
sort iso widcode year p
by iso widcode year: generate bracket_size = cond(_n == _N, 1 - p/1e5, (p[_n + 1] - p)/1e5)

// Integrate using trapezoidal rule
by iso widcode year: generate trapezoid = ((equality_line - bottom_share) + ///
	cond(_n == _N, 0, equality_line[_n + 1] - bottom_share[_n + 1]))*bracket_size/2
collapse (sum) value = trapezoid, by(iso widcode year data_quality)
replace value = 2*value

// Code as Gini
replace widcode = "g" + substr(widcode, 2, .)
generate p = "p0p100"

tempfile gini
save "`gini'"

// Save
*use "$work_data/calculate-pareto-coef-output.dta", clear
use `pareto_coef'

drop if substr(widcode, 1, 1) == "g"
append using "`gini'"

//------------------------------------------------------------------------------
// ----------------------- 4. checks for data quality --------------------------
//------------------------------------------------------------------------------

assert data_quality!=. if strpos(widcode, "ptinc") 
assert data_quality!=. if strpos(widcode, "cainc")
assert data_quality!=. if strpos(widcode, "diinc")
assert data_quality!=. if strpos(widcode, "hweal") & p!="p0p100" & p!="pall"
assert data_quality!=. if strpos(widcode, "fiinc") & p!="p0p100" & p!="pall"

bysort iso year widcode: assert data_quality == data_quality[1]

//------------------------------------------------------------------------------
// ----------------------------- 5. Export -------------------------------------
//------------------------------------------------------------------------------

compress
label data "Generated by calculate-coefficients.do"
save "$work_data/calculate-coefficients-output.dta", replace













