//----------------------------------------------------------------------------//
//---------------- Extend distributions 992 to 999 ---------------------------//
//----------------------------------------------------------------------------//


//----------- 1. call macroeconomic data (anninc) ----------------------------//
use "$work_data/merge-historical-main.dta", clear

keep if p=="p0p100"
keep if inlist(widcode, "anninc992i", "anninc999i", "ahweal992i","ahweal999i") //, "npopul992i","npopul999i")

keep iso year widcode value 
reshape wide value,i(iso year) j(widcode) string
rename value* *

gen rat_ptinc= anninc999i/anninc992i
gen rat_hweal= ahweal999i/ahweal992i
*gen rat_popul= npopul999i/npopul992i

drop anninc999i anninc992i ahweal999i ahweal992i

tempfile anninc
save "`anninc'"


//----------- 2. Keep data to be extended (anninc) ----------------------------//
u "$work_data/merge-historical-main.dta", clear

*Retain desired data
* Note: Notmally we should have ptinc since 1820 fro the core territories. Ptinc and Diinc from 1980 for all the countries,and hweal since 1995.
*drop if p=="p0p100"
keep if strpos(widcode, "ptinc992j") | strpos(widcode, "diinc992j")| strpos(widcode, "hweal992j") 
keep if inlist(substr(widcode, 1, 1), "s", "t", "a")

* Generate widcode sections
gen fivelet = substr(widcode,2,5)
gen onelet = substr(widcode,1,1)


*calibrate series to 999
merge n:1 iso year using "`anninc'", keep(master match) nogenerate


// ptinc (pretax national income) => direct rescaling on anninc
replace value = value * rat_ptinc if inlist(onelet, "t", "a") & inlist(fivelet, "diinc", "ptinc")
replace value = value * rat_hweal if inlist(onelet, "t", "a") & inlist(fivelet, "hweal")

* Rename their widcoode
replace widcode = onelet + fivelet + "999j"

drop fivelet onelet rat_ptinc rat_hweal

gen new=1
tempfile series999
save `series999'

//----------- 2. Add to the WID ----------------------------//
u "$work_data/merge-historical-main.dta", clear

append using "`series999'"


*Cleanning
duplicates tag iso year widcode p, gen(dup)
drop if dup==1 & new!=1
duplicates tag iso year widcode p, gen(dup2)
assert dup2==0
drop new dup*

//----------- 3. Add data quality to 999 variables & post-tax -----------------//

preserve
	keep if (strpos(widcode, "ptinc992j") | strpos(widcode, "diinc992j") | strpos(widcode, "ptinc999j") | strpos(widcode, "diinc999j") | strpos(widcode, "hweal992j") | strpos(widcode, "hweal999j"))
	gen fivelet = substr(widcode, 2, 5)
	gen ages = substr(widcode, 7, 3)
	
// confirm there is only 1 data quality value within each iso-year-ifvelet
	bys iso year fivelet: egen dq_n = nvals(data_quality)
	replace dq_n = 0 if mi(dq_n)
	assert dq_n <= 1  
	drop dq_n

// Assign data quality to diinc (both 992 and 999)
	bys iso year: egen quality_ptinc = max(cond(fivelet=="ptinc" & ages=="992", data_quality, .))
	assert quality_ptinc != . if (strpos(widcode, "ptinc") | strpos(widcode, "diinc"))

	replace data_quality = quality_ptinc if fivelet=="diinc"
	assert data_quality != . if fivelet=="diinc"

// Assign data quality to hweal999  
	bys iso year: egen quality_hweal = max(cond(fivelet=="hweal" & ages=="992", data_quality, .))
	*assert quality_hweal != . if fivelet=="hweal" // activate when wealth data quality is filled 

	replace data_quality = quality_hweal if fivelet=="hweal"
	*assert data_quality != . if fivelet=="hweal"

	keep iso year widcode data_quality
	duplicates drop
	tempfile dataquality 
	save `dataquality'
restore 

merge m:1 iso year widcode using `dataquality', update nogen 

assert data_quality!=. if strpos(widcode, "ptinc")
assert data_quality!=. if strpos(widcode, "cainc")
assert data_quality!=. if strpos(widcode, "diinc")

//----------- 4. Export ----------------------------//
label data "Generated by extend-distributions-999.do"
save "$work_data/extend-distributions-999-output.dta", replace
