//----------------------------------------------------------------------------//
//---------------- Extend distributions 992 to 999 ---------------------------//
//----------------------------------------------------------------------------//


//----------- 1. call macroeconomic data (anninc) ----------------------------//
use "$work_data/merge-historical-main.dta", clear

keep if p=="p0p100"
keep if inlist(widcode, "anninc992i", "anninc999i", "ahweal992i","ahweal999i") //, "npopul992i","npopul999i")

keep iso year widcode value 
reshape wide value,i(iso year) j(widcode) string
rename value* *

gen rat_ptinc= anninc999i/anninc992i
gen rat_hweal= ahweal999i/ahweal992i
*gen rat_popul= npopul999i/npopul992i

drop anninc999i anninc992i ahweal999i ahweal992i

tempfile anninc
save "`anninc'"


//----------- 2. Keep data to be extended (anninc) ----------------------------//
u "$work_data/merge-historical-main.dta", clear

*Retain desired data
* Note: Notmally we should have ptinc since 1820 fro the core territories. Ptinc and Diinc from 1980 for all the countries,and hweal since 1995.
*drop if p=="p0p100"
keep if strpos(widcode, "ptinc992j") | strpos(widcode, "diinc992j")| strpos(widcode, "hweal992j") 
keep if inlist(substr(widcode, 1, 1), "s", "t", "a")

* Generate widcode sections
gen fivelet = substr(widcode,2,5)
gen onelet = substr(widcode,1,1)


*calibrate series to 999
merge n:1 iso year using "`anninc'", keep(master match) nogenerate


// ptinc (pretax national income) => direct rescaling on anninc
replace value = value * rat_ptinc if inlist(onelet, "t", "a") & inlist(fivelet, "diinc", "ptinc")
replace value = value * rat_hweal if inlist(onelet, "t", "a") & inlist(fivelet, "hweal")

* Rename their widcoode
replace widcode = onelet + fivelet + "999j"

drop fivelet onelet rat_ptinc rat_hweal

gen new=1
tempfile series999
save `series999'

//----------- 2. Add to the WID ----------------------------//
u "$work_data/merge-historical-main.dta", clear

append using "`series999'"


*Cleanning
duplicates tag iso year widcode p, gen(dup)
drop if dup==1 & new!=1
duplicates tag iso year widcode p, gen(dup2)
assert dup2==0
drop new dup*

//----------- 3. Export ----------------------------//
label data "Generated by extend-distributions-999.do"
save "$work_data/extend-distributions-999-output.dta", replace
