//----------------------------------------------------------------------------//
//                   Import Bauluz et al.(2025)
//----------------------------------------------------------------------------//

clear all

tempfile combined
save `combined', emptyok

*Define globals
*global sheets D1a D1b D1c D1d D1e D1f D1g D1h D2a D2b D2c D2d D3a D3b D3c D3d D3e D4a D4b D4c D4d D4e D5a D5b D5c D5d
global sheets D1a D1b D1c D1d D1e D1f D1g D1h D2a D2b D2c D2d D3a D3b D3c D3d D3e D4a D4b D4c D4d D4e D5a D5b D5c

//-------- 1. Import data ----------------------------------------------------//
*foreach s in nweal pweal nwnxa {
*	import excel "$wid_dir/Country-Updates/Wealth/Historical_aggregates/pweal_1800_1979.xlsx", sheet("`s'") firstrow cellrange(A4:BO184) clear
foreach s in $sheets {
	di "Now reading: sheet `s'"
	quietly {
		import excel "$wid_dir/Country-Updates/WealthA_BBDMNOPSS2025/Bauluzetal2025Appendix.xlsx", sheet("`s'") cellrange(A1:A1) clear
		local def`s' = A[1]
		import excel "$wid_dir/Country-Updates/WealthA_BBDMNOPSS2025/Bauluzetal2025Appendix.xlsx", sheet("`s'") firstrow cellrange(A4:BO229) clear
		
		capture confirm variable A
		if !_rc {
			rename A year
		}
			
		* Tranforms the regions name into WID iso codes
		rename *, upper
		rename (WORLD EUROPE NORTHAMERICAOCEANIA LATINAMERICA MIDDLEEASTNORTHAFRICA) (WO QE XB XL XN)
		rename (SUBSAHARANAFRICA RUSSIACENTRALASIA EASTASIA SOUTHSOUTHEASTASIA) (XF XR QL XS)

		* Format to long
		rename * value*
		rename valueYEAR year

		reshape long value, i(year) j(iso) string
			
		*Label the data with the variable definition
		gen origin="`s'"
		gen concept="`def`s''"
			
		tempfile sheet`s'
		save "`sheet`s''"
			
		*Append to the other rest of the data
		use "`combined'", clear
		append using "`sheet`s''"
		save `combined', replace
	}
}

//-------- 2. Format data   --------------------------------------------------//
use "`combined'", clear

* cleaning
drop if missing(value)
replace concept = subinstr(concept, "Data series on ", "", .)
keep if year<=2022

* Generate widcodes
gen     widcode ="nwdka" if origin=="D1a"
replace widcode ="nweal" if origin=="D1b"
replace widcode ="nwnxa" if origin=="D1c"
replace widcode ="nwgxa" if origin=="D2a"
replace widcode ="nwgxd" if origin=="D2b"
replace widcode ="nnfin" if origin=="D3a"
replace widcode ="finrx" if origin=="D3b"
replace widcode ="finpx" if origin=="D3c"
replace widcode ="pweal" if origin=="D4a"
replace widcode ="gweal" if origin=="D4b"
replace widcode ="gwass" if origin=="D4d" // gwass=gwnfa+gwfin 
replace widcode ="gwdeb" if origin=="D4e"
replace widcode ="confc" if origin=="D5c"
drop if missing(widcode)

keep iso year widcode value 
reshape wide value, i(iso year) j(widcode) string

rename value* *

* Trasnform data to % of GDP
gen gdpro=1
gen ndpro=gdpro-confc


foreach var of varlist confc-pweal {
    replace `var' = `var' * ndpro
}

* Complete variables
gen nwnfa = nweal-nwnxa

*gen nninc= ndpro+nnfin
drop confc finrx finpx ndpro nnfin nwgxa nwgxd gdpro nwnxa // This data is, with higher detail in NievasPiketty2025 and Diertichetal2025

rename * value*
rename (valueiso valueyear) (iso year)

reshape long value, i(iso year) j(widcode) string

* Format WID code
replace widcode ="y"+ widcode + "999i"
gen p="pall"

gen q_ = 4
gen s_ = "bauluz25"

//-------- 3. Export data ----------------------------------------------------//
* Export full dataset
label data "Generated by import-bauluzetal2025.do"
save "$work_data/bauluzetal2025wealth_2025", replace

* Export historical Data
keep if year<=1980
save "$work_data/bauluzetal2025wealth_2025_hist", replace
