// -----------------------------------------------------------------------------
// 				Import Sector factor shares papers . do
//------------------------------------------------------------------------------

// 1. Import CFC from Bengston Waldenström
use "$project_dir/data-input/sector-factor-shares/BW_capitalsharedatabase_gross_net.dta", clear
rename Year year
countrycode Country, generate(iso) from("wb")
gen confc_BW =  Depreciationrate /100
gen confc_source = "BW"
replace confc_BW = . if confc_BW == 0 | confc_BW < 0
keep iso year confc_BW confc_source
drop if iso == "IT" | iso == "CA" |  iso == "BR" | iso == "FR" | iso == "GB" | iso == "AR"
label data "Generated by import-sectorfactor-shares-papers.do"
save "$work_data/BW_Historical_Factor_Share_Database.dta", replace

// 2. China Import China National Accounts from PYZ 2017 
import excel using "$project_dir/data-input/sector-factor-shares/CN_PYZ2017.xlsx", cellrange(A7:V45) clear firstrow
drop comhn
label data "Generated by import-sectorfactor-shares-papers.do"
save "$work_data/CN_PYZ2017.dta", replace

* 3. NPZ2014 for Russia
*---Use data from Piketty-Novokmet-Zucman including the Assumtion to keep 1980 sectoral shares constat until 1913, because very little self-employment
import excel using "$project_dir/data-input/sector-factor-shares/NPZ2017Appendix.xlsx", sheet("RU") cellrange(A7:AA223) clear firstrow
drop X W Y
label data "Generated by import-sectorfactor-shares-papers.do"
save "$work_data/NPZ2017.dta", replace

// 4. Load Historical Natinal Accounts of Sweden (Edvinsson2005)
import excel using "$project_dir/data-input/sector-factor-shares/Sweden_Edvinsson2005.xlsx", cellrange(A8:AA209) firstrow clear
label data "Generated by import-sectorfactor-shares-papers.do"
save "$work_data/SE_historical_account.dta", replace

// 5. National Accounts Saudi Arabia:
* --- unreaslistic 0 mixed income, use data from offical puplication
import excel "$project_dir/data-input/sector-factor-shares/SA_national_accounts.xlsx", sheet("SA")  cellrange(A7:AA30) firstrow clear
drop X W Y
drop gsrhn nsrhn ccshn
label data "Generated by import-sectorfactor-shares-papers.do"
save "$work_data/country_fix_SA.dta", replace 


// 6. Natural Accounts of  Peru by Cesar Castillo Garcia
* --- Use National accound data from  Castillo Garcia
*Import Data
import excel "$project_dir/data-input/sector-factor-shares/2026_02_08_Peru Paper Series.xlsx", sheet("Comparison Domestic Capital") cellrange(A2:H130) firstrow clear
keep A MarketPriceGDPsoles
rename (A MarketPriceGDPsoles) ( year mgdpro)
tempfile castillogarcia_gdp
save `castillogarcia_gdp'

import excel "$project_dir/data-input/sector-factor-shares/2026_02_08_Peru Paper Series.xlsx", sheet("GDP, CFC, NDP, NNI") cellrange(A2:M130) firstrow clear
keep    Year Laborincomecurrentsoles Mixedincomecurrentsoles T_productioncurrentsoles CFCcurrentsoles NetForeignIncome
rename (Year Laborincomecurrentsoles Mixedincomecurrentsoles T_productioncurrentsoles CFCcurrentsoles NetForeignIncome) (year mcomhn mgmxhn mptxgo mconfc mnnfin)


merge 1:1 year using "`castillogarcia_gdp'", nogenerate
	
* Calcualte Y shares
* Calcualte variables as percentage of GDP
	foreach x in  comhn gmxhn ptxgo confc nnfin{
	gen _`x'=m`x'/mgdpro
}


* Keep onluy relevant variables
keep year _* // keep only year and percentages of GDP
rename _* *
drop if year>2022
keep if year>=1942
gen iso="PE"

*generate gvato
gen gvato= 1- ptxgo

/*
foreach v in comhn gmxhn ptxgo confc nnfin ndpro nninc {
	gen data_quality_y`v'= 4 if !missing(y`v')
	gen source_y`v'= "garciacastillo" if !missing(y`v')
}
*/
gen series =0

label data "Generated by import-sectorfactor-shares-papers.do"
save "$work_data/castillogarcia2026.dta", replace 
