*import delimited "$imf_data/world-economic-outlook/WEO-$pastyear.csv", ///
	clear varnames(1) encoding("utf8") // delimiter(",") 
	
// 2026 update: import excel file directly instead of csv 
import excel "$imf_data/world-economic-outlook/WEO-$pastyear.xlsx", sheet("Countries") firstrow clear
rename *, lower

cap dropmiss, obs force
cap dropmiss, obs
drop dataset series_code countryid indicator-methodology_notes historical_data_source-primary_domestic_currency
ds country indicatorid, not

foreach v of varlist `r(varlist)' { // UP2026: adapted loop slightly for excel format
	local year: var label `v'
	if ("`year'" == "") {
		drop `v'
	}
	else {
		destring `v', replace force ignore(",")
		rename `v' value`year'
	}
}

keep if indicatorid == "NGDP_D" | indicatorid == "PPPEX"
*drop iso weocountrycode subjectdescriptor units ///
	scale countryseriesspecificnotes
replace country = "Côte d'Ivoire"         if country == "C�te d'Ivoire"
replace country = "São Tomé and Príncipe" if country == "S�o Tom� and Pr�ncipe"
replace country="Côte d'Ivoire"           if (country == "Cte d'Ivoire" | country == "CÙte d'Ivoire")
replace country="São Tomé and Príncipe"   if (country == "So Tom and Prncipe" | country == "S„o TomÈ and PrÌncipe")
replace country="Turkey" 				  if country == "T¸rkiye"
replace country = "Swaziland"             if country == "Eswatini"
replace country = "Democratic Republic of the Congo" if country == "Congo, Democratic Republic of the"
replace country = substr(country, 1, strpos(country, ",") - 1) if strpos(country, ",") > 0 // correcting country names 

countrycode country, generate(iso) from("imf weo")
drop country 

rename valueLATEST_ACTUAL_ANNUAL_DATA estimatesstartafter

reshape long value, i(iso indicatorid) j(year)
// adding this to ensure reshape results in no duplicate iso-year obs
bys iso: egen esa_fill = max(estimatesstartafter)
replace estimatesstartafter = esa_fill if missing(estimatesstartafter)
drop esa_fill

reshape wide value, i(iso year) j(indicatorid) string

// Zimbabwe: IMF moved to RTGS dollars unlike other databases: convert back to USD
replace valueNGDP_D = valueNGDP_D/valuePPPEX if iso == "ZW"
drop valuePPPEX


rename valueNGDP_D def_imf

drop if def_imf >= .

drop if year >=$year  // we are taking 2021 estimates

rename def_imf def_weo

label data "Generated by import-imf-weo-deflator.do"
save "$work_data/imf-deflator-weo.dta", replace
