********************************************************************************
* 2024

import delimited "$wb_data/ppp/API_PA.NUS.PPP_DS2_en_csv_v2_$year.csv", ///
	clear encoding("utf8") rowrange(3) varnames(4) 

// Rename year variables
cap dropmiss
cap dropmiss, force
foreach v of varlist v*{
	local year: variable label `v'
	rename `v' value`year'
}

// Identify countries
replace countryname = "Macedonia, FYR" if countryname == "North Macedonia"
replace countryname = "Swaziland"      if countryname == "Eswatini"
replace countryname = "Korea, Dem. People's Rep." if countryname == "Korea, Dem. People's Rep."
replace countryname = "Vietnam" if countryname == "Viet Nam"

countrycode countryname, generate(iso) from("wb")

// Add currency from the metadata
merge n:1 countryname using "$work_data/wb-metadata.dta", ///
	keep(master match) nogenerate // Regions are dropped

// Identify currencies
replace currency = "turkmenistan manat" if currency == "New Turkmen manat"
replace currency = "u.s. dollar"        if currency == "Liberian dollar"
replace currency = "vietnamese dong"    if countryname=="Vietnam"

currencycode currency, generate(currency_iso) iso2c(iso) from("wb")
drop currency
rename currency_iso currency

keep iso currency value*

reshape long value, i(iso) j(year)

drop if value >= .

rename value ppp_wb

*keep if year == 2011
gegen max_year = max(year), by(iso)
//-------------------------------------------
*Note:The PPP are ment to pass from LCU to USD PPP. Given that we treat the data in USD for special country cases, these needs to be correcte as follows. Check section PartMain.1 of import-exchange-rate.do.
merge 1:1 iso year using  "$work_data/exchange-rates-cases.dta", nogenerate keep(master match) keepusing(exrate_usd)

replace ppp_wb=ppp_wb/exrate_usd if inlist(iso, "ZW") //,  "LR" , "SV", "EC")
drop exrate_usd
//-------------------------------------------

keep if year == min(2021, max_year)
drop max_year

label data "Generated by import-ppp-wb.do"
save "$work_data/ppp-wb.dta", replace
