// -----------------------------------------------------------------------------
// 				Import Sector factor shares papers . do
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// 1. Import CFC from Bengston Waldenström
// 2. China Import China National Accounts from PYZ 2017 
// 3. NPZ2014 for Russia
// 4. Load Historical Natinal Accounts of Sweden (Edvinsson2005)
// 5. National Accounts Saudi Arabia:
// 6. Natural Accounts of  Peru by Cesar Castillo Garcia
//------------------------------------------------------------------------------

// 1. Import CFC from Bengston Waldenström -------------------------------------
use "$project_dir/data-input/sector-factor-shares/BW_capitalsharedatabase_gross_net.dta", clear
rename Year year
countrycode Country, generate(iso) from("wb")
gen confc_BW =  Depreciationrate /100

replace confc_BW = . if confc_BW == 0 | confc_BW < 0
keep iso year confc_BW 
drop if iso == "IT" | iso == "CA" |  iso == "BR" | iso == "FR" | iso == "GB" | iso == "AR"

gen s_confc_BW = "Waldenstrom" if !missing(confc_BW) // https://wid.world/document/what-determines-the-capital-share-world-inequality-lab-wp-2020-08/
gen q_confc_BW = 4  if !missing(confc_BW) 

label data "Generated by import-sectorfactor-shares-papers.do"
save "$work_data/BW_Historical_Factor_Share_Database.dta", replace

// 2. China Import China National Accounts from PYZ 2017 -----------------------
import excel using "$project_dir/data-input/sector-factor-shares/CN_PYZ2017.xlsx", cellrange(A7:V45) clear firstrow
drop comhn

ds iso year, not
foreach v in `r(varlist)' {
	gen q_`v'= 4 if !missing(`v')
	gen s_`v'= "PikettyYangZucman2017" if !missing(`v') //https://wid.world/document/t-piketty-l-yang-and-g-zucman-capital-accumulation-private-property-and-inequality-in-china-1978-2015-2016/

}

label data "Generated by import-sectorfactor-shares-papers.do"
save "$work_data/CN_PYZ2017.dta", replace

// 3. NPZ2014 for Russia -------------------------------------------------------
*---Use data from Piketty-Novokmet-Zucman including the Assumtion to keep 1980 sectoral shares constat until 1913, because very little self-employment
import excel using "$project_dir/data-input/sector-factor-shares/NPZ2017Appendix.xlsx", sheet("RU") cellrange(A7:AA223) clear firstrow
drop X W Y

ds iso year, not
foreach v in `r(varlist)' {
	gen q_`v'= 4 if !missing(`v')
	gen s_`v'= "NovokmetPikettyZucman2017" if !missing(`v') // https://wid.world/document/appendix-soviets-oligarchs-inequality-property-russia-1905-2016-wid-world-working-paper-201710/
}

label data "Generated by import-sectorfactor-shares-papers.do"
save "$work_data/NPZ2017.dta", replace

// 4. Load Historical Natinal Accounts of Sweden (Edvinsson2005) ---------------
import excel using "$project_dir/data-input/sector-factor-shares/Sweden_Edvinsson2005.xlsx", cellrange(A8:AA209) firstrow clear
drop W X Y
ds iso year, not
foreach v in `r(varlist)' {
	gen q_`v'= 4 if !missing(`v')
	gen s_`v'= "Edvinsson2005" if !missing(`v') // https://www.diva-portal.org/smash/get/diva2:193148/FULLTEXT01.pdf
}

label data "Generated by import-sectorfactor-shares-papers.do"
save "$work_data/SE_historical_account.dta", replace

// 5. National Accounts Saudi Arabia: ------------------------------------------
* --- unreaslistic 0 mixed income, use data from offical puplication
import excel "$project_dir/data-input/sector-factor-shares/SA_national_accounts.xlsx", sheet("SA")  cellrange(A7:AA30) firstrow clear
drop X W Y
drop gsrhn nsrhn ccshn

ds iso year, not
foreach v in `r(varlist)' {
	gen q_`v'= 4 if !missing(`v')
	gen s_`v'= "SAGAStat" if !missing(`v') 
}

label data "Generated by import-sectorfactor-shares-papers.do"
save "$work_data/country_fix_SA.dta", replace 


// 6. Natural Accounts of  Peru by Cesar Castillo Garcia -----------------------
* --- Use National accound data from  Castillo Garcia
*Import Data
import excel "$project_dir/data-input/sector-factor-shares/2026_02_08_Peru Paper Series.xlsx", sheet("Comparison Domestic Capital") cellrange(A2:H130) firstrow clear
keep A MarketPriceGDPsoles
rename (A MarketPriceGDPsoles) ( year mgdpro)
tempfile castillogarcia_gdp
save `castillogarcia_gdp'

import excel "$project_dir/data-input/sector-factor-shares/2026_02_08_Peru Paper Series.xlsx", sheet("GDP, CFC, NDP, NNI") cellrange(A2:M130) firstrow clear
keep    Year Laborincomecurrentsoles Mixedincomecurrentsoles T_productioncurrentsoles CFCcurrentsoles NetForeignIncome
rename (Year Laborincomecurrentsoles Mixedincomecurrentsoles T_productioncurrentsoles CFCcurrentsoles NetForeignIncome) (year mcomhn mgmxhn mptxgo mconfc mnnfin)


merge 1:1 year using "`castillogarcia_gdp'", nogenerate
	
* Calcualte Y shares
* Calcualte variables as percentage of GDP
	foreach x in  comhn gmxhn ptxgo confc nnfin{
	gen _`x'=m`x'/mgdpro
}


* Keep onluy relevant variables
keep year _* // keep only year and percentages of GDP
rename _* *
drop if year>2022
keep if year>=1942
gen iso="PE"

*generate gvato
gen gvato= 1- ptxgo

ds iso year, not
 foreach v in `r(varlist)' {
	gen q_`v'= 4 if !missing(`v')
	gen s_`v'= "castillogarcia2026" if !missing(`v') 
}

gen series =0

label data "Generated by import-sectorfactor-shares-papers.do"
save "$work_data/castillogarcia2026.dta", replace 
