//------------------------------------------------------------------------------
//           Import WTO tradeMerchandise.do
//------------------------------------------------------------------------------

// importing raw data
import delimited using "$wid_dir/Country-Updates/Trade/WTOTradeMerchandise/merchandise_values_annual_dataset_$year.csv", clear

keep if partner == "World"

gen flow = "export" if indicator == "Merchandise exports by product group - annual"
replace flow = "import" if indicator == "Merchandise imports by product group - annual"

keep reportercode reporteriso reporter partner productcode product unit year valueflagcode valueflag value flow

// assign iso2 codes
kountry reporteriso, from(iso3c) to(iso2c)
ren _ISO2C_ iso 

tab reporter if mi(iso)

replace iso = "BE" if reporter == "Belgium-Luxembourg"
replace iso = "BQ" if reporter == "Bonaire, Sint Eustatius and Saba"
replace iso = "TW" if reporter == "Chinese Taipei"
replace iso = "CW" if reporter == "Curaçao"
replace iso = "CZ" if reporter == "Czech and Slovak Federal Republic"
replace iso = "ET" if reporter == "Ethiopia (+ Eritrea)"
replace iso = "GF" if reporter == "French Guiana"
replace iso = "TF" if reporter == "French Southern Territories"
replace iso = "DE" if reporter == "German Democratic Republic"
replace iso = "DE" if reporter == "Germany, Federal Republic of"
replace iso = "GP" if reporter == "Guadeloupe"
replace iso = "MQ" if reporter == "Martinique"
replace iso = "AN" if reporter == "Netherlands Antilles (incl. Aruba)"
replace iso = "MP" if reporter == "Northern Mariana Islands"
replace iso = "RE" if reporter == "Reunion"
replace iso = "RO" if reporter == "Romania"
replace iso = "RS" if reporter == "Serbia and Montenegro"
replace iso = "SX" if reporter == "Sint Maarten"
replace iso = "TK" if reporter == "Tokelau"
replace iso = "SU" if reporter == "U.S.S.R."
replace iso = "YE" if reporter == "Yemen, Arab Republic of"
replace iso = "YE" if reporter == "Yemen, People's Democratic Republic"
replace iso = "YU" if reporter == "Yugoslavia, Socialist Federal Republic of"

drop if mi(iso)

// summing at the country-year product level
collapse (sum) value, by(iso year productcode product flow)
order iso year flow productcode product value 
so iso year flow productcode


/* classification
productcode	product
AG			Agricultural products
	AGFO		Food
	
MA			Manufactures
	MACH		Chemicals
		MACHPH		Pharmaceuticals
	MACL		Clothing
	MAIS		Iron and steel
	MAMT		Machinery and transport equipment
		MAMTAU		Automotive products
		MAMTOF		Office and telecom equipment
		MAMTOTEP	Electronic data processing and office equipment
		MAMTOTIC	Integrated circuits and electronic components
		MAMTOTTL	Telecommunications equipment
		MAMTTE		Transport equipment
	MATE		Textiles
	
MI		Fuels and mining products
	MIFU	Fuels
	
TO		Total merchandise
*/

// keeping Agricultural, Manufacturing, Fuel mining and Total
keep if inlist(productcode, "AG", "MA", "MI", "TO")
drop product

tab productcode if year < 1980 // before 1980 only total
drop if year < 1980

gen type = flow + productcode
drop flow productcode
reshape wide value, i(iso year) j(type) string
renvars value*, predrop(5)

gen check = (exportAG + exportMA + exportMI)/exportTO // does not match
drop check 

replace exportTO = exportAG + exportMA + exportMI
replace importTO = importAG + importMA + importMI

foreach v in AG MA MI {
	gen sh_exp_`v' = export`v'/exportTO
}
foreach v in AG MA MI {
	gen sh_imp_`v' = import`v'/importTO
}

// generate metadata

foreach x in exp imp {
	foreach v in AG MA MI {
		gen q_`x'ort`v'  = 5           if !missing(`x'ort`v')
		gen s_`x'ort`v'  = "WTOtrade"  if !missing(`x'ort`v')
		gen q_sh_`x'_`v' = 5           if !missing(sh_`x'_`v')
		gen s_sh_`x'_`v' = "WTOtrade"  if !missing(sh_`x'_`v')
	}
}

quality exportAG exportMA exportMI, gen(q_exportTO)
gen s_exportTO = "exportAG,exportMA,exportMI" if !missing(q_exportTO)
quality importAG importMA importMI, gen(q_importTO)
gen s_importTO = "importAG,importMA,importMI" if !missing(q_importTO)


// Export
label data "Generated by import-wto-trademerchandise.do"
save  "$work_data/merchandisetrade.dta", replace
