*import delimited "$imf_data/world-economic-outlook/WEO-$pastyear.csv", ///
	clear varnames(1) encoding("utf8") //    delimiter(",") 

// 2026 update: import excel file directly instead of csv 
import excel "$imf_data/world-economic-outlook/WEO-$pastyear.xlsx", sheet("Countries") firstrow clear
rename *, lower

cap dropmiss, obs force
cap dropmiss, obs
drop dataset series_code countryid indicator-methodology_notes historical_data_source-primary_domestic_currency
ds country indicatorid, not


foreach v of varlist `r(varlist)' { // UP2026: adapted loop slightly for excel format
	local year: var label `v'
	if ("`year'" == "") {
		drop `v'
	}
	else {
		destring `v', replace force ignore(",")
		rename `v' value`year'
	}
}

keep if indicatorid == "NGDP" | indicatorid == "PPPEX"
*drop iso weocountrycode subjectdescriptor units ///
	scale countryseriesspecificnotes
replace country = "Côte d'Ivoire"         if country == "C�te d'Ivoire"
replace country = "São Tomé and Príncipe" if country == "S�o Tom� and Pr�ncipe"
replace country="Côte d'Ivoire"           if (country == "Cte d'Ivoire" | country == "CÙte d'Ivoire")
replace country="São Tomé and Príncipe"   if (country == "So Tom and Prncipe" | country == "S„o TomÈ and PrÌncipe")
replace country="Turkey" 				  if country == "T¸rkiye"
replace country = "Swaziland"             if country == "Eswatini"
replace country = "Democratic Republic of the Congo" if country == "Congo, Democratic Republic of the"
replace country = substr(country, 1, strpos(country, ",") - 1) if strpos(country, ",") > 0 // correcting country names 

countrycode country, generate(iso) from("imf weo")
drop country

rename valueLATEST_ACTUAL_ANNUAL_DATA estimatesstartafter
reshape long value, i(iso indicatorid estimatesstartafter) j(year)
reshape wide value, i(iso year estimatesstartafter) j(indicatorid) string


// keeping VEN PPP
preserve
	keep if iso == "ZW"
	keep iso year valuePPPEX
	ren valuePPPEX ppp_imf
	keep if year == $pastyear
	sa "$work_data/imf-zw-pppex", replace
restore 


// Zimbabwe: IMF moved to RTGS dollars unlike other databases: convert back to USD
*replace valueNGDP = valueNGDP/valuePPPEX if iso == "ZW"
drop if iso== "ZW"
// keeping VEN PPP
preserve
	keep if iso == "VE"
	keep iso year valuePPPEX
	ren valuePPPEX ppp_imf
	keep if year == $pastyear
	sa "$work_data/imf-ven-pppex", replace
restore 

// keeping AD PPP
preserve
	keep if iso == "AD"
	keep iso year valuePPPEX
	ren valuePPPEX ppp_imf
	keep if year == $pastyear
	sa "$work_data/imf-ad-pppex", replace
restore 

// keeping TW PPP
preserve
	keep if iso == "TW"
	keep iso year valuePPPEX
	ren valuePPPEX ppp_imf
	keep if year == $pastyear
	sa "$work_data/imf-tw-pppex", replace
restore 

// keeping SS PPP
preserve
	keep if iso == "SS"
	keep iso year valuePPPEX
	ren valuePPPEX ppp_imf
	keep if year == $pastyear
	sa "$work_data/imf-ss-pppex", replace
restore 

drop valuePPPEX


drop if value >= .

qui sum estimatesstartafter
drop if year > `r(max)'

replace value = value*1e9
rename value gdp_lcu_weo

drop if year == $year 

label data "Generated by import-imf-weo-gdp.do"
save "$work_data/imf-weo-gdp.dta", replace
