// ============================================================================= //------------------------ DATA QUALITY ----------------------------------------
// =============================================================================


// Objective: to collect all the data quality for all countries into one file.
//			  An almost-complete file exists already as an excel, so this is to
// 			  complete the file with its missing counties (mainly Europe, LATM)

// NOTE: this will eventually become obsolete as we transition to the new 
// 		 data_quality approach which varies by year. This is simply a placeholder. 


// By Ana Van Der Ree, November 2025. 

// -----------------------------------------------------------------------------

// --------------------- 0. Set up directory -----------------------------------
do "~/Documents/GitHub/wid-world/stata-do/setup.do"

// ---------------1. call current excel file -----------------------------------
// the data_quality which is being called into final metadata
import delimited "$input_data_dir/data-quality/data-quality.csv", clear delim(";") stringcols(_all)
cap ren ïiso iso
	keep iso quality
	gsort iso
	
// ---------------- 2. Add Europe countries data quality -----------------------
preserve
	use "$wid_dir/Country-Updates/Europe/2024_09/wid-world-var-notes.dta", clear
	keep iso data_quality
	duplicates drop
	tempfile europe
	save `europe'
restore

append using `europe'

// ---------------- 3. Add Latin America countries data quality ----------------
preserve
	use "$wid_dir/Country-Updates/Latin_America/2024_10/dina_latam_3Oct2024.dta", clear
	keep iso data_quality
	duplicates drop
	tempfile latm
	save `latm'
restore

append using `latm'

tostring quality data_quality, replace


// ---------------- 4. Add Asia countries data quality ----------------
preserve
	use "$wid_dir/Country-Updates/Asia/2024_9/Data submission/Asia-full-2024-metadata.dta", clear
	keep iso data_quality
	duplicates drop
	tempfile asia
	save `asia'
restore

append using `asia'

// ---------------- 5. Add Mena countries data quality ----------------
preserve
	use "$wid_dir/Country-Updates/Middle-East/2024/DINA_MiddleEast_AUG2024.dta", clear
	keep iso data_quality
	duplicates drop
	tempfile mena
	save `mena'
restore

append using `mena'

// ---------------- 6. Add NAOC countries data quality ----------------
preserve
	use "$wid_dir/Country-Updates/North_America/2024_09/AUCANZ_all_2024-metadata.dta", clear
	append using "$wid_dir/Country-Updates/US/2024/US_all_2024-metadata.dta"
	keep iso data_quality
	duplicates drop
	tempfile naoc
	save `naoc'
restore

append using `naoc'

// ----------------- 4. Clean up duplicate countries ---------------------------

duplicates tag iso, gen(dup)
sort dup iso

// specific fixes where there are more than 2 duplicates (ie. dup==2)
replace quality = "3" if iso =="CN"
replace quality = "1" if iso =="ID"
replace quality = "1" if iso =="MY"
replace quality = "3" if iso =="SG"
replace quality = "3" if iso =="TH"

bysort iso: keep if dup < 2 | _n == 1

// correcting countries with updated data_quality
replace quality = data_quality if dup==1

// specific fixes where data_quality is missing but quality isnt
replace quality = "3" if inlist(iso, "CN-UR", "CN-RU", "HK")
replace quality = "0" if inlist(iso, "KP", "MO")
replace quality = "1" if iso =="MN"

drop if data_quality == "." & dup==1 & !inlist(iso, "KP", "MN", "MO")
bysort iso: drop if inlist(iso, "KP", "MN", "MO") & _n == 2

// correcting countries that weren't in the file before
replace quality = data_quality if quality == ""

duplicates tag iso, gen(dup2)
assert dup2 == 0

drop data_quality dup dup2

sort iso
isid iso

// ----------------- 5. Export data quality ------------------------------------
label data "Generated by grab-data-quality.do"
save "$input_data_dir/data-quality/data-quality-updated.dta", replace




